services:
  worker-ingest:
    command: celery -A fluxdb.celery_app.celery_app worker --loglevel=INFO -Q ingest --concurrency=2

  worker-export:
    command: celery -A fluxdb.celery_app.celery_app worker --loglevel=INFO -Q export --concurrency=1

  postgres:
    command: >
      postgres
      -c shared_buffers=2GB
      -c effective_cache_size=6GB
      -c maintenance_work_mem=512MB
      -c work_mem=32MB
      -c wal_compression=on
      -c max_wal_size=12GB
      -c checkpoint_timeout=15min
      -c checkpoint_completion_target=0.9
      -c random_page_cost=1.1
      -c effective_io_concurrency=150
